version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  hash-python:
    lang: python3-http
    handler: ./hash-python
    image: haolangao/hash-python:latest
    replicas: 1
